config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end

  resources :credit_cards, only: [:new] do
    collection do
      get 'show', to: 'credit_cards#show'
      post 'pay', to: 'credit_cards#pay'
      post 'delete', to: 'credit_cards#delete'
    end
  end

  root 'items#index'
  resources :items do
    collection do
      get 'signup'
      get 'search'
      get 'ransack'
      get 'get_category_children', defaults: { fomat: 'json'}
      get 'get_category_grandchildren', defaults: { fomat: 'json'}
    end
    member do
      post   '/like/:item_id', to: 'likes#like',   as: 'like'
      delete '/like/:item_id', to: 'likes#unlike', as: 'unlike'
    end
    resources :messages, only:[:create,:update,:destroy] do
      member do
        get 'restore'
      end
    end
    resources :purchase, only: [:index] do
      collection do
        post 'pay', to: 'purchase#pay'
        get 'done', to: 'purchase#done'
      end
    end
  end

  resources :categories, only: [:index] do
    member do
      get 'parent'
      get 'child'
      get 'grandchild'
    end
  end
   
  resources :mypages, only: [:index] do
    collection do
      get 'logout'
      get :likes
    end
  end
  scope :mypages do
    resources :cards, only: [:index]
  end
end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
  belongs_to :user
end

app/controllers/credit_cards_controller.rb
class CreditCardsController < ApplicationController

  require "payjp"
  before_action :set_card, only:[:show, :delete]
  before_action :category_parent_array, only: [:new, :show]


  def new
    @card = CreditCard.where(user_id: current_user.id)
    redirect_to action: "show" if @card.exists?
  end

  
  def pay #payjpとCardのデータベース作成を実施します。
    Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
    if params['payjp-token'].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create(
        # description: '登録テスト', #なくてもOK
        # email: current_user.email, #なくてもOK
        card: params['payjp-token'],
        metadata: {user_id: current_user.id}
      ) #念の為metadataにuser_idを入れましたがなくてもOK
      @card = CreditCard.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to action: "show"
      else
        redirect_to action: "pay"
      end
    end
  end
  
  
  def delete #PayjpとCardデータベースを削除します
    if @card.present?
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(@card.customer_id)
      customer.delete
      @card.delete
    end
    redirect_to action: "new"
  end
  

  def show
    if @card.blank?
      redirect_to action: "new" 
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @default_card_information = customer.cards.retrieve(@card.card_id)
      @default_card_brand = @default_card_information.brand      
      case @default_card_brand
      when "Visa"
        @default_card_src = "visa.svg"
      when "JCB"
        @default_card_src = "jcb.svg"
      when "MasterCard"
        @default_card_src = "master-card.svg"
      when "American Express"
        @default_card_src = "american_express.svg"
      when "Diners Club"
        @default_card_src = "dinersclub.svg"
      when "Discover"
        @default_card_src = "discover.svg"
      when "SaisonCard"
        @default_card_src = "saison-card.svg"
      end
    end
  end

  private
  def set_card
    @card = CreditCard.where(user_id: current_user.id).first
  end

  def category_parent_array
    @category_parent_array = Category.where(ancestry: nil) 
  end

end

app/helpers/credit_card_helper.rb
module CreditCardHelper
end

app/views/credit_cards/new.html.haml
= render partial: "items/header"
.Mypage
  .Mypage__Wrapper
    .Mypage__Wrapper__Side
      %ul
        %li.Mypage__Wrapper__Side__list
          = link_to "マイページ", mypages_path
          = icon('fa','chevron-right')
        %li.Mypage__Wrapper__Side__list
          = link_to "お知らせ", "#"
          = icon('fa','chevron-right')
        %li.Mypage__Wrapper__Side__list
          = link_to "いいね！一覧", "#"
          = icon('fa','chevron-right')
        %li.Mypage__Wrapper__Side__list
          = link_to "出品する", "#"
          = icon('fa','chevron-right')
        %li.Mypage__Wrapper__Side__list
          = link_to "出品した商品-出品中", "#"
          = icon('fa','chevron-right')
        %li.Mypage__Wrapper__Side__list
          = link_to "出品した商品-売却済み", "#"
          = icon('fa','chevron-right')
        
      %ul.Mypage__Wrapper__Side__unli  
        設定
        %li.Mypage__Wrapper__Side__list
          = link_to "プロフィール", "#"
          = icon('fa','chevron-right')
        %li.Mypage__Wrapper__Side__list
          = link_to "発送元・お届け先住所変更", "#"
          = icon('fa','chevron-right')
        %li.Mypage__Wrapper__Side__list
          = link_to "支払い方法", cards_path, class: "PageActive"
          = icon('fa','chevron-right')
        %li.Mypage__Wrapper__Side__list
          = link_to "メール/パスワード", "#"
          = icon('fa','chevron-right')
        %li.Mypage__Wrapper__Side__list
          = link_to "本人情報", "#"
          = icon('fa','chevron-right')
        %li.Mypage__Wrapper__Side__list
          = link_to "ログアウト", logout_mypages_path
          = icon('fa','chevron-right')
    .Mypage__Wrapper__Main
      %section.mypage-content__chapter-container
        %h2.card-main__chapter-head
          クレジットカード情報入力
        = form_tag(pay_credit_cards_path, method: :post, id: 'charge-form', class: 'card-main__inner card-main__inner--registration-form',  name: "inputForm") do
          .card-main__content
            .card-main__form-group
              %label カード番号
              %span.card-main__form-require 必須
              = text_field_tag "number", "", class: "card-main__input-default", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
              %ul.signup-main__has-error-text
              %ul.card-main__card-list
                %li
                  = image_tag asset_path("visa.svg"), width: '49', height: '20'
                %li
                  = image_tag asset_path("master-card.svg"), width: '34', height: '20'
                %li
                  = image_tag asset_path("saison-card.svg"), width: '30', height: '20'
                %li
                  = image_tag asset_path("jcb.svg"), width: '32', height: '20'
                %li
                  = image_tag asset_path("american_express.svg"), width: '21', height: '20'
                %li
                  = image_tag asset_path("dinersclub.svg"), width: '32', height: '20'
                %li
                  = image_tag asset_path("discover.svg"), width: '32', height: '20'
            .card-main__form-group.card-main__form-expire
              %label 有効期限
              %span.card-main__form-require 必須
              %br
              .card-main__select-wrap.card-main__select-wrap--half
                %select#exp_month{name: "exp_month", type: "text", class: 'card-main__month__select'}
                  %option{value: ""} --
                  %option{value: "1"}01
                  %option{value: "2"}02
                  %option{value: "3"}03
                  %option{value: "4"}04
                  %option{value: "5"}05
                  %option{value: "6"}06
                  %option{value: "7"}07
                  %option{value: "8"}08
                  %option{value: "9"}09
                  %option{value: "10"}10
                  %option{value: "11"}11
                  %option{value: "12"}12
                = icon 'fas', 'chevron-down'
                %span 月
              .card-main__select-wrap.card-main__select-wrap--half
                %select#exp_year{name: "exp_year", type: "text", class: 'card-main__month__select'}
                  %option{value: ""} --
                  %option{value: "2019"}19
                  %option{value: "2020"}20
                  %option{value: "2021"}21
                  %option{value: "2022"}22
                  %option{value: "2023"}23
                  %option{value: "2024"}24
                  %option{value: "2025"}25
                  %option{value: "2026"}26
                  %option{value: "2027"}27
                  %option{value: "2028"}28
                  %option{value: "2029"}29
                = icon 'fas', 'chevron-down'
                %span 年
              %ul.card-main__has-error-text
              %ul.card-main__has-error-text
            .card-main__form-group
              %label セキュリティコード
              %span.card-main__form-require 必須
              = text_field_tag "cvc", "", class: "card-main__input-default", placeholder: "カード背面4桁もしくは3桁の番号", maxlength: "4", id: "cvc"
              %ul.card-main__has-error-text
              .card-main__seqcode
                .card-main__seqcode__text
                  %span.card-main__form-question
                    ?
                  カード裏面の番号とは？
                .card-main__seqcode__info.is-show
                  カードの裏面をご参照ください。
                  %br
                  = image_tag asset_path("seq-card.png"), type: '', width: '240'
            %p.card-main__has-error-text
              #card_token.card-main__form-group
              = submit_tag "追加する", id: "token_submit", class: 'card-main__btn-default card-main__btn-red'

app/views/credit_cards/show.html.haml
= render partial: "items/header"
.Mypage
  .Mypage__Wrapper
    .Mypage__Wrapper__Side
      %ul
        %li.Mypage__Wrapper__Side__list
          = link_to "マイページ", mypages_path
          = icon('fa','chevron-right')
        %li.Mypage__Wrapper__Side__list
          = link_to "お知らせ", "#"
          = icon('fa','chevron-right')
        %li.Mypage__Wrapper__Side__list
          = link_to "いいね！一覧", "#"
          = icon('fa','chevron-right')
        %li.Mypage__Wrapper__Side__list
          = link_to "出品する", "#"
          = icon('fa','chevron-right')
        %li.Mypage__Wrapper__Side__list
          = link_to "出品した商品-出品中", "#"
          = icon('fa','chevron-right')
        %li.Mypage__Wrapper__Side__list
          = link_to "出品した商品-売却済み", "#"
          = icon('fa','chevron-right')
        
      %ul.Mypage__Wrapper__Side__unli  
        設定
        %li.Mypage__Wrapper__Side__list
          = link_to "プロフィール", "#"
          = icon('fa','chevron-right')
        %li.Mypage__Wrapper__Side__list
          = link_to "発送元・お届け先住所変更", "#"
          = icon('fa','chevron-right')
        %li.Mypage__Wrapper__Side__list
          = link_to "支払い方法", cards_path, class: "PageActive"
          = icon('fa','chevron-right')
        %li.Mypage__Wrapper__Side__list
          = link_to "メール/パスワード", "#"
          = icon('fa','chevron-right')
        %li.Mypage__Wrapper__Side__list
          = link_to "本人情報", "#"
          = icon('fa','chevron-right')
        %li.Mypage__Wrapper__Side__list
          = link_to "ログアウト", logout_mypages_path
          = icon('fa','chevron-right')
    .Mypage__Wrapper__Main
      %section.mypage-content__chapter-container
        %h2.card-main__chapter-head
          支払い方法
        .card-main__inner
          %section
            .card-main__content
              %h3.card-main__chapter-sub-head
                クレジットカード一覧
            %ul.mypage-content__payment-list
              %li
                .card-main__content.card-main__content-form{ action: '#', method: 'GET' }
                  %div
                    = image_tag "#{@default_card_src}", width: '49', height: '15', alt: @default_card_brand, id: "card_image",class:"card__card-main__mask__contents__content__menu__brand"
                  .mypage-content__payment-num
                    = "**** **** **** " + @default_card_information.last4
                  .mypage-content__payment-num
                    - exp_month = @default_card_information.exp_month.to_s
                    - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
                    = exp_month + ' / ' + exp_year
                  = form_tag(delete_credit_cards_path, method: :post, id: 'charge-form',  name: 'inputForm', class: 'mypage-content__card--form') do
                    %input{ type: 'hidden', name: 'card_id', value: '' }
                    %button.mypage-content__payment-remove 削除する
          .mypage-content__not-regist
            = link_to '#', target: '_blank' do
              %span 支払い方法について
              = icon 'fas', 'chevron-right'