config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end

  resources :credit_cards, only: [:new] do
    collection do
      get 'show', to: 'credit_cards#show'
      post 'pay', to: 'credit_cards#pay'
      post 'delete', to: 'credit_cards#delete'
    end
  end

  root 'items#index'
  resources :items do
    collection do
      get 'signup'
      get 'search'
      get 'ransack'
      get 'get_category_children', defaults: { fomat: 'json'}
      get 'get_category_grandchildren', defaults: { fomat: 'json'}
    end
    member do
      post   '/like/:item_id', to: 'likes#like',   as: 'like'
      delete '/like/:item_id', to: 'likes#unlike', as: 'unlike'
    end
    resources :messages, only:[:create,:update,:destroy] do
      member do
        get 'restore'
      end
    end
    resources :purchase, only: [:index] do
      collection do
        post 'pay', to: 'purchase#pay'
        get 'done', to: 'purchase#done'
      end
    end
  end

  resources :categories, only: [:index] do
    member do
      get 'parent'
      get 'child'
      get 'grandchild'
    end
  end
   
  resources :mypages, only: [:index] do
    collection do
      get 'logout'
      get :likes
    end
  end
  scope :mypages do
    resources :cards, only: [:index]
  end
end

app/controllers/mypages_controller.rb
class MypagesController < ApplicationController

  before_action :category_parent_array

  def index
  end

  def logout
  end

  private
  def category_parent_array
    @category_parent_array = Category.where(ancestry: nil) 
  end
end

app/helpers/mypages_helper.rb
module MypagesHelper
end

app/views/mypages/index.html.haml
- breadcrumb :mypage

= render partial: "items/header"
= render partial: "items/breadcrumbs"
.Mypage
  .Mypage__Wrapper
    .Mypage__Wrapper__Side
      %ul
        %li.Mypage__Wrapper__Side__list
          = link_to "マイページ", mypages_path, class: "PageActive"
          = icon('fa','chevron-right')
        %li.Mypage__Wrapper__Side__list
          = link_to "お知らせ", "#"
          = icon('fa','chevron-right')
        %li.Mypage__Wrapper__Side__list
          = link_to "いいね！一覧", likes_mypages_path
          = icon('fa','chevron-right')
        %li.Mypage__Wrapper__Side__list
          = link_to "出品する", new_item_path
          = icon('fa','chevron-right')
        %li.Mypage__Wrapper__Side__list
          = link_to "出品した商品-出品中", "#"
          = icon('fa','chevron-right')
        %li.Mypage__Wrapper__Side__list
          = link_to "出品した商品-売却済み", "#"
          = icon('fa','chevron-right')
        
      %ul.Mypage__Wrapper__Side__unli  
        設定
        %li.Mypage__Wrapper__Side__list
          = link_to "プロフィール", "#"
          = icon('fa','chevron-right')
        %li.Mypage__Wrapper__Side__list
          = link_to "発送元・お届け先住所変更", "#"
          = icon('fa','chevron-right')
        %li.Mypage__Wrapper__Side__list
          = link_to "支払い方法", cards_path
          = icon('fa','chevron-right')
        %li.Mypage__Wrapper__Side__list
          = link_to "メール/パスワード", "#"
          = icon('fa','chevron-right')
        %li.Mypage__Wrapper__Side__list
          = link_to "本人情報", "#"
          = icon('fa','chevron-right')
        %li.Mypage__Wrapper__Side__list
          = link_to "ログアウト", logout_mypages_path
          = icon('fa','chevron-right')
    .Mypage__Wrapper__Main
      .Mypage__Wrapper__Main__user-name
        = "#{current_user.nickname}さんのマイページ"
= render partial: "items/footer"

app/views/mypages/likes.html.haml
= render partial: "items/header"
.Mypage
  .Mypage__Wrapper
    .Mypage__Wrapper__Side
      %ul
        %li.Mypage__Wrapper__Side__list
          = link_to "マイページ", mypages_path
          = icon('fa','chevron-right')
        %li.Mypage__Wrapper__Side__list
          = link_to "お知らせ", "#"
          = icon('fa','chevron-right')
        %li.Mypage__Wrapper__Side__list
          = link_to "いいね！一覧", likes_mypages_path, class: "PageActive"
          = icon('fa','chevron-right')
        %li.Mypage__Wrapper__Side__list
          = link_to "出品する", new_item_path
          = icon('fa','chevron-right')
        %li.Mypage__Wrapper__Side__list
          = link_to "出品した商品-出品中", "#"
          = icon('fa','chevron-right')
        %li.Mypage__Wrapper__Side__list
          = link_to "出品した商品-売却済み", "#"
          = icon('fa','chevron-right')
        
      %ul.Mypage__Wrapper__Side__unli  
        設定
        %li.Mypage__Wrapper__Side__list
          = link_to "プロフィール", "#"
          = icon('fa','chevron-right')
        %li.Mypage__Wrapper__Side__list
          = link_to "発送元・お届け先住所変更", "#"
          = icon('fa','chevron-right')
        %li.Mypage__Wrapper__Side__list
          = link_to "支払い方法", cards_path
          = icon('fa','chevron-right')
        %li.Mypage__Wrapper__Side__list
          = link_to "メール/パスワード", "#"
          = icon('fa','chevron-right')
        %li.Mypage__Wrapper__Side__list
          = link_to "本人情報", "#"
          = icon('fa','chevron-right')
        %li.Mypage__Wrapper__Side__list
          = link_to "ログアウト", logout_mypages_path
          = icon('fa','chevron-right')
    .Mypage__Wrapper__Main
      .main
      %section.main-table
      %h2.main__table__header
        いいね！一覧
      %ul.main__table__list
        - current_user.like_items.each do |item|
          %li
            =link_to item_path(item), class: "main__table__list__item" do
              .image
                = image_tag item.item_images.first.image.url , size: '48x64'
              .main__table__list__item__body
                .main__table__list__item__body__text
                = item.name
                %br
                = item.price 
                円
              .icon
                .fas.fa-chevron-right
= render partial: "items/footer"

app/views/mypages/logout.html.haml
- breadcrumb :mypage_logout

= render partial: "items/header"
= render partial: "items/breadcrumbs"

.Mypage
  .Mypage__Wrapper
    .Mypage__Wrapper__Side
      %ul
        %li.Mypage__Wrapper__Side__list
          = link_to "マイページ", mypages_path
          = icon('fa','chevron-right')
        %li.Mypage__Wrapper__Side__list
          = link_to "お知らせ", "#"
          = icon('fa','chevron-right')
        %li.Mypage__Wrapper__Side__list
          = link_to "いいね！一覧", likes_mypages_path
          = icon('fa','chevron-right')
        %li.Mypage__Wrapper__Side__list
          = link_to "出品する", new_item_path
          = icon('fa','chevron-right')
        %li.Mypage__Wrapper__Side__list
          = link_to "出品した商品-出品中", "#"
          = icon('fa','chevron-right')
        %li.Mypage__Wrapper__Side__list
          = link_to "出品した商品-売却済み", "#"
          = icon('fa','chevron-right')
        
      %ul.Mypage__Wrapper__Side__unli  
        設定
        %li.Mypage__Wrapper__Side__list
          = link_to "プロフィール", "#"
          = icon('fa','chevron-right')
        %li.Mypage__Wrapper__Side__list
          = link_to "発送元・お届け先住所変更", "#"
          = icon('fa','chevron-right')
        %li.Mypage__Wrapper__Side__list
          = link_to "支払い方法", cards_path
          = icon('fa','chevron-right')
        %li.Mypage__Wrapper__Side__list
          = link_to "メール/パスワード", "#"
          = icon('fa','chevron-right')
        %li.Mypage__Wrapper__Side__list
          = link_to "本人情報", "#"
          = icon('fa','chevron-right')
        %li.Mypage__Wrapper__Side__list
          = link_to "ログアウト", logout_mypages_path, class: "PageActive"
          = icon('fa','chevron-right')
    .Mypage__Wrapper__Main
      .Mypage__Wrapper__Main__logout
        = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "Mypage__Wrapper__Main__logout--link"
= render partial: "items/footer"