config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end

  resources :credit_cards, only: [:new] do
    collection do
      get 'show', to: 'credit_cards#show'
      post 'pay', to: 'credit_cards#pay'
      post 'delete', to: 'credit_cards#delete'
    end
  end

  root 'items#index'
  resources :items do
    collection do
      get 'signup'
      get 'search'
      get 'ransack'
      get 'get_category_children', defaults: { fomat: 'json'}
      get 'get_category_grandchildren', defaults: { fomat: 'json'}
    end
    member do
      post   '/like/:item_id', to: 'likes#like',   as: 'like'
      delete '/like/:item_id', to: 'likes#unlike', as: 'unlike'
    end
    resources :messages, only:[:create,:update,:destroy] do
      member do
        get 'restore'
      end
    end
    resources :purchase, only: [:index] do
      collection do
        post 'pay', to: 'purchase#pay'
        get 'done', to: 'purchase#done'
      end
    end
  end

  resources :categories, only: [:index] do
    member do
      get 'parent'
      get 'child'
      get 'grandchild'
    end
  end
   
  resources :mypages, only: [:index] do
    collection do
      get 'logout'
      get :likes
    end
  end
  scope :mypages do
    resources :cards, only: [:index]
  end
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  validates :name, length: { maximum: 40 }, presence: true
  validates :introduction, :condition_id, :category, :price, :shipping_charge_id, :prefecture_id, :shipping_day_id, presence: true
  validates :price, numericality: {greater_than: 299, less_than: 9999999 }
  validates :item_images, presence: true

  has_many :likes, dependent: :destroy
  has_many :liking_users, through: :likes, source: :user
  has_many :messages, dependent: :destroy
  has_many :item_images, dependent: :destroy
  accepts_nested_attributes_for :item_images, allow_destroy: true
  
  belongs_to :category
  belongs_to :seller, class_name: 'User', foreign_key: 'seller_id'
  belongs_to :buyer, class_name: 'User', foreign_key: 'buyer_id', optional: true
  belongs_to_active_hash :prefecture
  belongs_to_active_hash :condition
  belongs_to_active_hash :shipping_charge
  belongs_to_active_hash :shipping_day

  def precious
    Item.order('created_at desc, id desc').where('created_at <= ? and id < ?', created_at, id).first
  end

  def next
    Item.order('created_at desc, id desc').where('created_at >= ? and id > ?', created_at, id).reverse.first
  end

  def self.search(search)
    return Item.all unless search
    Item.where('name LIKE(?)', "%#{search}%")
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, only: :new
  before_action :category_parent_array, except: [:destroy]
  before_action :set_items, only: [:edit, :update, :destroy, :show]
  before_action :set_ransack, only: [:search, :ransack]



  def index
    @items = Item.includes(:item_images).order('created_at DESC').limit(4)
  end

  def new
    @item = Item.new
    @item.item_images.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else 
      render :new
    end
  end

  def show
    @images = @item.item_images
    @category_id = @item.category_id
    @category_parent = Category.find(@category_id).parent.parent
    @category_child = Category.find(@category_id).parent
    @category_grandchild = Category.find(@category_id)
    @message = Message.new
    @messages = @item.messages.includes(:user)
  end

  def edit
  end
  
  def update
    if @item.update(item_params)
      redirect_to item_path(@item.id)
    else 
      render :edit
    end
  end

  def destroy
    redirect_to edit_item_path notice: "削除に失敗しました" unless @item.destroy
  end

  def search
    @keyword = params[:keyword]
    @items = Item.search(params[:keyword])
  end

  def ransack
    @ransack = @q.result(distinct: true)
    if params[:q].present?
      @namekey = params[:q][:name_cont]
    else
      params[:q] = {sorts: 'id asc'}
    end
  end


  # 子カテゴリー
  def get_category_children
    @category_children = Category.find("#{params[:parent_id]}").children
  end
  # 孫カテゴリー
  def get_category_grandchildren
    @category_grandchildren = Category.find("#{params[:child_id]}").children
  end
  
  private

  def category_parent_array
    @category_parent_array = Category.where(ancestry: nil)
  end

  def set_items
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:name, :introduction, :price, :category_id,
      :condition_id, :prefecture_id, :shipping_charge_id, :shipping_day_id, 
      :brand, :buyer_id, :seller_id, item_images_attributes: [:image,:_destroy, :id]).merge(seller_id: current_user.id)
  end

  def set_ransack
    @q = Item.ransack(params[:q])
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_breadcrumbs.html.haml
%nav.List-box
  %ul.List-menu
    %li.List-menu__content
      = breadcrumbs separator: "&nbsp;&#62;&nbsp;"

app/views/items/_category.html.haml
.category
  = link_to "カテゴリー", "#"
  %ul.category__parent.category__list
    - @category_parent_array.each do |parent|
      %li
        = link_to parent_category_path(id: parent), class: "category__parent__name" do
          = parent.name
        %ul.category__child.category__list
          - parent.children.each do |child|
            %li
              = link_to child_category_path(id: child), class: "category__child__name" do
                = child.name
              %ul.category__grandchild.category__list
                - child.children.each do |grandchild|
                  %li
                    = link_to grandchild_category_path(id: grandchild), class: " category__child__name" do
                      = grandchild.name 
    %li
      = link_to "#", class: "category__parent__name" do
        カテゴリー一覧

app/views/items/_footer.html.haml
%footer
  .Footer-img
    .Footer-img__area
      = image_tag asset_path("bg-appBanner-pict.jpg"), class: "visual"
      .Footer-img__area__text
        今すぐ無料ダウンロード！

  .Footer-lists
    .Footer-lists__content
      .Footer-lists__content__head
        FURIMAについて
      %ul
        %li.Footer-lists__content__text
          会社概要（運営会社）
        %li.Footer-lists__content__text
          プライバシーポリシー
        %li.Footer-lists__content__text
          FURIMA利用規約
        %li.Footer-lists__content__text
          ポイントに関する特約

    .Footer-lists__content
      .Footer-lists__content__head
        FURIMAを見る
      %ul
        %li.Footer-lists__content__text
          カテゴリー一覧
        %li.Footer-lists__content__text
          ブランド一覧

    .Footer-lists__content
      .Footer-lists__content__head
        ヘルプ＆ガイド
      %ul
        %li.Footer-lists__content__text
          FURIMAガイド
        %li.Footer-lists__content__text
          FURIMAロゴ利用ガイドライン
        %li.Footer-lists__content__text
          お知らせ

  .Footer-icon
    = image_tag asset_path("logo-white.png"), size: "160x46"
    ©︎FURIMA
    

app/views/items/_form.html.haml
.product-container
  = render 'items/form_header'
  .product-form
    = form_with model: @item, local: true do |f|
      .product-form__image-container
        %p.message
          商品出品画像
          %span.style_attention.required
            必須
        %p.image-message
          最大10枚までアップロード出来ます
        .upload-space
          .icon
            #image-box
              #previews
                - if @item.persisted?
                  - @item.item_images.each_with_index do |image, i|
                    .preview
                      = image_tag image.image.url, data: { index: i }, width: "100", height: '100', class: "preview-image"
                      .js-remove 削除
              %label{class: "icon", id: "image-label", for: "item_item_images_attributes_#{@item.item_images.count}_image"}
                = icon("fas", "camera")
                = f.fields_for :item_images do |image|
                  .js-file_group{"data-index" => "#{image.index}"}
                    = image.file_field :image, class: 'js-file'
                  - if @item.persisted?
                    = image.check_box :_destroy, data:{ index: image.index }, class: 'hidden-destroy'
                - if @item.persisted?
                  .js-file_group{"data-index": "#{@item.item_images.count}"}
                    = file_field_tag :item_image, name: "item[item_images_attributes][#{@item.item_images.count}][image]", class: 'js-file', id: "item_item_images_attributes_#{@item.item_images.count}_image"
                .icon-comment
                  %p#text カメラをクリックしてファイルをアップロード
      .product-form__item-container
        %p.message
          商品名
          %span.style_attention.required
            必須  
          -if @item.errors.messages[:name].any?
            .error-message
              入力してください
        .input-field
          = f.text_field :name, class: "product-form__item-container__name-box",  placeholder: "商品名（必須 40文字まで)"
        %p.message
          商品の説明
          %span.style_attention.required
            必須
          -if @item.errors.messages[:introduction].any?
            .error-message
              入力してください
        .input-field 
          = f.text_area :introduction, class: "product-form__item-container__description-box", placeholder: "商品の説明"
      .product-form__details-container
        %h3.explanation
          商品の詳細
        %p.message
          カテゴリー
          %span.style_attention.required
            必須
          -if @item.errors.messages[:category_id].any?
            .error-message
              選択してください
        .category-form
          = f.collection_select :category_id, @category_parent_array, :id, :name,{ include_blank: "選択してください"}, {class: "product-form__details-container__category-box", id: 'parent_category'}
        %p.message
          ブランド
          %span.style_attention.any
            任意
        = f.text_field :brand, class: "product-form__details-container__brand-box",  placeholder: "例) シャネル"    
        %p.message
          商品の状態
          %span.style_attention.required
            必須
          -if @item.errors.messages[:condition_id].any?
            .error-message
              選択してください
        .input-field
          = f.collection_select :condition_id, Condition.all, :id, :name, {prompt: "選択してください"}, {class: "product-form__details-container__condition-box"}
      .product-form__post-container
        %h3.explanation
          配送について
        %p.message
          配送料
          %span.style_attention.required
            必須
          -if @item.errors.messages[:shipping_charge_id].any?
            .error-message
              選択してください
        .input-field
          = f.collection_select :shipping_charge_id, ShippingCharge.all, :id, :name, {prompt: "選択してください"}, {class: "product-form__post-container__shipping-charge-box"}
        %p.message
          配送元
          %span.style_attention.required
            必須
          -if @item.errors.messages[:prefecture_id].any?
            .error-message
              選択してください
        .input-field
          = f.collection_select :prefecture_id, Prefecture.all, :id, :name, {prompt: "選択してください"}, {class: "product-form__post-container__shipping-charge-box"} 
        %p.message
          配送までの日数
          %span.style_attention.required
            必須
          -if @item.errors.messages[:shipping_day_id].any?
            .error-message 
              選択してください  
        .input-field
          = f.collection_select :shipping_day_id, ShippingDay.all, :id, :name, {prompt: "選択してください"}, {class: "product-form__post-container__shipping-charge-box"}
      .product-form__price-container
        %h3.explanation
          販売価格(300〜9,999,999)  
        %ul
          %li
            %p.message-price
              販売価格
              %span.style_attention.required
                必須
          %li
            .price
              %span ¥
              =f.number_field :price, placeholder: "0", type: "number", class: "product-form__price-container__price-box"
        -if @item.errors.messages[:shipping_day_id].any?
          .error-message-price
            300以上9,999,999以下で入力してください 
      .product-form__submit-container
        .product-form__submit-container__button
          %input{type: "submit", class: "product-form__submit-container__exhibition", value: "出品する"}
        - if @item.persisted?
          .product-form__submit-container__button
            = link_to "この商品を削除する", item_path(@item.id), method: :delete, class: "product-form__submit-container__exhibition", data: {confirm: "削除しますか？"}
        .product-form__submit-container__back
          = link_to root_path do
            もどる
      .product-form__attention-container
        %p.sub-message
          禁止されている
          = link_to "#" do
            行為
          および
          = link_to "#" do
            出品物
          を必ずご確認ください。
          = link_to "#" do
            偽ブランド品
          や
          = link_to "#" do
            盗品物
          などの販売は犯罪であり、法律により処罰される可能性があります。 また、出品をもちまして
          = link_to "#" do
            加盟店規約
          同意したことになります。
  = render 'items/form_footer'

app/views/items/_form_footer.html.haml
.product-footer
  %ul.product-footer__clearfix
    %li.product-footer__clearfix__message
      = link_to "#" do
        プライバシーポリシー
    %li.product-footer__clearfix__message
      = link_to "#" do
        メルカリ利用規約
    %li.product-footer__clearfix__message
      = link_to "#" do
        特定商取引に関する表記
  .product-footer__logo
    = link_to root_path do
      = image_tag asset_path("logo.png"), size: "140x55"
    %p.product-footer__logo__message ©️FURIMA

app/views/items/_header.html.haml
%header
  .main
    = link_to new_item_path do
      .exhibition
        .exhibition__button
          出品する
          .icon
            = image_tag asset_path("icon_camera.png"), size: "54x54"
    = link_to root_path do
      = image_tag asset_path("logo.png"), class: "main__img", size: "140x40"
    = form_with url: search_items_path, local: true, method: :get, class: "main__form" do |f|
      = f.text_field :keyword, placeholder: "キーワードから探す", class: "main__form__input"
      = image_submit_tag asset_path("icon-search 1.png"), class: "main__form__button"
   
  .contents
    .contents__left
      = render 'items/category'
      .brand
        ブランド
    .contents__right
      - if user_signed_in?
        .login
          = link_to "マイページ", mypages_path
        .register
          = link_to "ログアウト", destroy_user_session_path, method: :delete
      -else
        .login
          = link_to "ログイン", new_user_session_path
        .register
          = link_to "新規会員登録", signup_items_path

app/views/items/destroy.html.haml
.product-container
  .product-header
    = link_to root_path do
      = image_tag asset_path("logo.png"), size: "150x65"
  .Destroy-wrapper
    .Success
      商品を削除しました
    = link_to root_path do
      .Toppage-link
        トップページへ戻る

  .product-footer
    %ul.product-footer__clearfix
      %li.product-footer__clearfix__message
        = link_to "#" do
          プライバシーポリシー
      %li.product-footer__clearfix__message
        = link_to "#" do
          メルカリ利用規約
      %li.product-footer__clearfix__message
        = link_to "#" do
          特定商取引に関する表記
    .product-footer__logo
      = link_to root_path do
        = image_tag asset_path("logo.png"), size: "140x55"
      %p.product-footer__logo__message ©️FURIMA
    

app/views/items/new.html.haml
= render 'items/form'

app/views/items/ransack.html.haml
= render partial: "items/header"

.Search
  .Search__Wrapper
    .Search__Wrapper__Side
      = search_form_for @q, url: ransack_items_path, class: "Search__Wrapper__Side__Form"  do |f|
  
        = f.select( :sorts, { '並び替え': 'id asc', '価格の安い順': 'price asc', '価格の高い順': 'price desc', '出品の新しい順': 'updated_at desc'}, {selected: params[:q][:sorts]}, { onchange: 'this.form.submit()', class: 'Search__Wrapper__Side__Form__sorts'})
        .Search__Wrapper__Side__Form__input
          .Search__Wrapper__Side__Form__input__text
            詳細検索
          .Search__Wrapper__Side__Form__input__cont
            .Search__Wrapper__Side__Form__input__cont__title
              キーワードを検索する
            = f.search_field :name_cont, placeholder: "例）値下げ", class: "Search__Wrapper__Side__Form__input__cont__box"
          .Search__Wrapper__Side__Form__input__cont
            .Search__Wrapper__Side__Form__input__cont__title
              ブランド名から探す
            = f.search_field :brand_cont, placeholder: "例）シャネル", class: "Search__Wrapper__Side__Form__input__cont__box"
          .Search__Wrapper__Side__Form__input__price
            .Search__Wrapper__Side__Form__input__price__title
              価格
            .Search__Wrapper__Side__Form__input__price__box
              = f.search_field :price_gteq, placeholder: "¥ Min", class: "Search__Wrapper__Side__Form__input__price__box__left"
              %p 〜
              = f.search_field :price_lteq, placeholder: "¥ Max", class: "Search__Wrapper__Side__Form__input__price__box__right"
          .Search__Wrapper__Side__Form__input__check
            .Search__Wrapper__Side__Form__input__check__title
              商品の状態
            %label.Search__Wrapper__Side__Form__input__check__box
              %input{type: "checkbox"}
                すべて
            .Search__Wrapper__Side__Form__input__check__boxes
              = f.collection_check_boxes :condition_id_in, Condition.all, :id, :name 
          .Search__Wrapper__Side__Form__input__check
            .Search__Wrapper__Side__Form__input__check__title
              配送料の負担
            %label.Search__Wrapper__Side__Form__input__check__box
              %input{type: "checkbox"}
                すべて
            .Search__Wrapper__Side__Form__input__check__boxes
              = f.collection_check_boxes :shipping_day_id_in, ShippingDay.all, :id, :name 
            
            
          .Search__Wrapper__Side__Form__input__submit
            = link_to "クリア", ransack_items_path, class: "Search__Wrapper__Side__Form__input__submit__clear"
            = f.submit "完了", class: "Search__Wrapper__Side__Form__input__submit__box"

    .Search__Wrapper__Main 
      %h2.Search__Wrapper__Main__result
        -if @namekey.present?
          = @namekey
          %span の検索結果
        -else 
          検索結果
      .Search__Wrapper__Main__number
        = "#{@ransack.count}件の表示"
      .Search__Wrapper__Main__items
        - @ransack.each do |i|
          = link_to item_path(i.id), class: "Search__Wrapper__Main__items__box" do
            .Search__Wrapper__Main__items__box__image
              = image_tag asset_path("#{i.item_images.first.image}"), size: "160x160"
            .Search__Wrapper__Main__items__box__text
              .Search__Wrapper__Main__items__box__text__field
                = i.name
            .Search__Wrapper__Main__items__box__price
              = "¥#{i.price}"
            
= render partial: "items/footer"

app/views/items/search.html.haml
- breadcrumb :search

= render partial: "items/header"
= render partial: "items/breadcrumbs"

.Search
  .Search__Wrapper
    .Search__Wrapper__Side
      = search_form_for @q, url: ransack_items_path, class: "Search__Wrapper__Side__Form"  do |f|
  
        = f.select( :sorts, { '並び替え': 'id asc', '価格の安い順': 'price asc', '価格の高い順': 'price desc', '出品の新しい順': 'updated_at desc'}, {}, { onchange: 'this.form.submit()', class: 'Search__Wrapper__Side__Form__sorts'})
        .Search__Wrapper__Side__Form__input
          .Search__Wrapper__Side__Form__input__text
            詳細検索
          .Search__Wrapper__Side__Form__input__cont
            .Search__Wrapper__Side__Form__input__cont__title
              キーワードを検索する
            = f.search_field :name_cont, placeholder: "例）値下げ", class: "Search__Wrapper__Side__Form__input__cont__box"
          .Search__Wrapper__Side__Form__input__cont
            .Search__Wrapper__Side__Form__input__cont__title
              ブランド名から探す
            = f.search_field :brand_cont, placeholder: "例）シャネル", class: "Search__Wrapper__Side__Form__input__cont__box"
          .Search__Wrapper__Side__Form__input__price
            .Search__Wrapper__Side__Form__input__price__title
              価格
            .Search__Wrapper__Side__Form__input__price__box
              = f.search_field :price_gteq, placeholder: "¥ Min", class: "Search__Wrapper__Side__Form__input__price__box__left"
              %p 〜
              = f.search_field :price_lteq, placeholder: "¥ Max", class: "Search__Wrapper__Side__Form__input__price__box__right"
          .Search__Wrapper__Side__Form__input__check
            .Search__Wrapper__Side__Form__input__check__title
              商品の状態
            %label.Search__Wrapper__Side__Form__input__check__box
              %input{type: "checkbox"}
                すべて
            .Search__Wrapper__Side__Form__input__check__boxes
              = f.collection_check_boxes :condition_id_in, Condition.all, :id, :name 
          .Search__Wrapper__Side__Form__input__check
            .Search__Wrapper__Side__Form__input__check__title
              配送料の負担
            %label.Search__Wrapper__Side__Form__input__check__box
              %input{type: "checkbox"}
                すべて
            .Search__Wrapper__Side__Form__input__check__boxes
              = f.collection_check_boxes :shipping_day_id_in, ShippingDay.all, :id, :name 
            
            
          .Search__Wrapper__Side__Form__input__submit
            = link_to "クリア", ransack_items_path, class: "Search__Wrapper__Side__Form__input__submit__clear"
            = f.submit "完了", class: "Search__Wrapper__Side__Form__input__submit__box"

    .Search__Wrapper__Main
      %h2.Search__Wrapper__Main__result
        -if @keyword.present?
          = @keyword
          %span の検索結果
        -else 
          検索結果
      .Search__Wrapper__Main__number
        = "#{@items.count}件の表示"
      .Search__Wrapper__Main__items
        - @items.each do |i|
          = link_to item_path(i.id), class: "Search__Wrapper__Main__items__box" do
            .Search__Wrapper__Main__items__box__image
              = image_tag asset_path("#{i.item_images.first.image}"), size: "160x160"
            .Search__Wrapper__Main__items__box__text
              .Search__Wrapper__Main__items__box__text__field
                = i.name
            .Search__Wrapper__Main__items__box__price
              = "¥#{i.price}"
            
= render partial: "items/footer"

app/views/items/show.html.haml
- breadcrumb :item_show, @item

%body
  = render partial: "header"

  .Wrapper
    = render partial: "breadcrumbs"
    .Container
      .Items
        %p.Items__title
          = @item.name
        .Items__img-first
          = image_tag "#{@images.first.image}", size: "500x400"
        .Items__img-second
          - @images.each do |i|
            = image_tag "#{i.image}", size: "160x120"

        %p.Items__price
          = "¥#{@item.price}"
        %p.Items__sipping
          (税込) 送料込み
        %p.Items__introduction
          = @item.introduction
        %table.Menu
          %tr.Menu__list
            %td.Menu__list__left
              出品者
            %td.Menu__list__right
              = @item.seller.nickname
          %tr.Menu__list
            %td.Menu__list__left
              カテゴリ
            %td.Menu__list__right
              = link_to "#{@category_parent.name}", parent_category_path(id: @category_parent)
              %br
              = link_to "#{@category_child.name}", child_category_path(id: @category_child)
              %br
              = link_to "#{@category_grandchild.name}", grandchild_category_path(id: @category_grandchild)
              %br
          %tr.Menu__list
            %td.Menu__list__left
              ブランド
            %td.Menu__list__right
              = @item.brand
          %tr.Menu__list
            %td.Menu__list__left
              商品の状態
            %td.Menu__list__right
              = @item.condition.name
          %tr.Menu__list
            %td.Menu__list__left
              配送料の負担
            %td.Menu__list__right
              = @item.shipping_charge.name
          %tr.Menu__list
            %td.Menu__list__left
              発送元の地域
            %td.Menu__list__right
              = @item.prefecture.name
          %tr.Menu__list
            %td.Menu__list__left
              発送日の目安
            %td.Menu__list__right
              = @item.shipping_day.name

        .Btn-area
          - if user_signed_in? && current_user.id == @item.seller_id
            .Items-btn.seller-btn
              = link_to edit_item_path(@item.id) do
                編集・削除はこちらから
          
          - elsif @item.buyer_id.present?
            .item-purchase
              ※この商品は既に購入されております

          - elsif user_signed_in? && current_user.id != @item.seller_id
            .Items-btn.buyer-btn
              = link_to item_purchase_index_path(@item.id) do
                購入する

          - else
            .Items-btn.login-btn
              = link_to new_user_session_path do
                .login-btn__top
                  ※ログインすると購入できます。
                .login-btn__down
                  ログインはこちらから

        .Option-area
          .Favorite
            = render partial: 'likes/like', locals: { item: @item }
          .Report
            不適切な商品の通報

      .item-detail-message
        .message-container
          .message-content
            - if user_signed_in?
              %ul.message-items
                - @messages.each do |message|
                  - if message.user_id == current_user.id  #コメントユーザーとカレントユーザーが同一の場合
                    .comment_Me.comment_one_block{data:{index: message.id}} 
                      %li.message-self
                        - if message.delete_check == 1   # 仮削除状態の場合
                          .message-body
                            .message-body-text
                              出品者によりこのコメントは削除されました。
                          - if message.item.seller_id == current_user.id  #カレントユーザーが出品者である場合
                            .comment_restore{data:{index: message.id, item: @item.id}}
                              = link_to "復元する",restore_item_message_path(item_id: @item, id: message.id)
                            .comment_delete.complete_delete{data:{index: message.id, item: @item.id}}    
                              = link_to '削除する', item_message_path(item_id: @item, id: message.id) , method: :delete
                        - else #仮削除状態でない場合
                          .comment_user_name
                            = message.user.nickname
                          .message-body
                            .message-body-text
                              -# = safe_join(message.message.split("\n"),tag(:br))  改行表示
                              = message.message
                              .message-icons
                                = message.created_at.strftime("%Y年%m月%d日 %H時%M分")
                          - if message.item.seller_id == current_user.id  #ログイン中のユーザーが出品者である場合
                            .comment_delete.me_pre_delete{data:{index: message.id, item: @item.id}}  
                              = link_to '削除する', item_message_path(item_id: @item, id: message.id) , method: :patch
                  - else #コメントユーザーとログインユーザーが異なる（他人のコメント）の場合 
                    .comment_Other.comment_one_block{data:{index: message.id}}    
                      %li.message-self
                        - if message.delete_check == 1   # 仮削除状態の場合
                          .message-body-other
                            .message-body-text
                              出品者によりこのコメントは削除されました。
                          - if message.item.seller_id == current_user.id  #ログイン中のユーザーが出品者である場合
                            .comment_restore{data:{index: message.id, item: @item.id}}
                              = link_to "復元する",restore_item_message_path(item_id: @item, id: message.id)
                            .comment_delete.complete_delete{data:{index: message.id, item: @item.id}}
                              = link_to '削除する', item_message_path(item_id: @item, id: message.id) , method: :delete
                        - else #仮削除状態でない場合
                          .comment_user_name_other
                            = message.user.nickname
                          .message-body-other
                            .message-body-text
                              -# = safe_join(message.message.split("\n"),tag(:br))  改行表示
                              = message.message
                              .message-icons
                                = message.created_at.strftime("%Y年%m月%d日 %H時%M分")
                          - if message.item.seller == current_user  #ログイン中のユーザーが出品者である場合
                            .comment_delete.other_pre_delete{data:{index: message.id, item: @item.id}}  
                              = link_to '削除する', item_message_path(item_id: @item, id: message.id) , method: :patch
          .message-content
            = form_with model: [@item, @message], class: "massage-form", local: true do |f|
              %p 
                相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
              = f.text_area :message, id:"comment_body", class: "textarea-default", wrap: "soft"
              = f.hidden_field :item_id, value: @item.id
              = f.submit "コメントする", class: "message-submit btn-default btn-gray"
              

      %ul.Move-area
        - if @item.next.present?
          %li.Next
            .Next__icon
              = icon('fas', 'angle-left')
            .Next__link
              = link_to item_path(@item.next) do
                前の商品
        - else
          %li.Next

        - if @item.precious.present?
          %li.Prev
            .Prev__link
              = link_to item_path(@item.precious) do
                後ろの商品
            .Prev__icon
              = icon('fas', 'angle-right')
        - else
          %li.Prev

      .Recommend
        .Recommend__link
          = link_to "ベビー・キッズをもっと見る", "#"
        .Recommend__category
          .recommend__category__img
            = image_tag asset_path('inu.jpg'), size: "220x150"
          .Recommend__category__content
            .Recommend__left
              .Recommend__left__title
                product2
              .Recommend__left__price
                ¥30000
              .Recommend__left__sipping
                （税込み）
            .Recommend__right
              ★０
  %footer
    = render partial: "footer"

app/views/items/signup.html.haml
.AccountPage
  .AccountPage__sessionLogo
    = link_to root_path do
      = image_tag asset_path("logo.png"), size: "185x49"
  .AccountPage__guidebox
    .AccountPage__guidebox__title
      新規会員登録
    .AccountPage__guidebox__regist
      .AccountPage__guidebox__regist__content
        = link_to new_user_registration_path, class: "AccountPage__guidebox__regist__content__mail" do
          %i.far.fa-envelope メールアドレスで登録する
        = link_to user_google_oauth2_omniauth_authorize_path, method: :post, class: "AccountPage__guidebox__regist__content__google" do
          = image_tag asset_path("medium.jpg"), size: "28x28"
          Googleで登録する
        = link_to user_facebook_omniauth_authorize_path, method: :post, class: "AccountPage__guidebox__regist__content__facebook" do
          %i.fab.fa-facebook-square Facebookで登録する
.SignupBlank  
    