config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end

  resources :credit_cards, only: [:new] do
    collection do
      get 'show', to: 'credit_cards#show'
      post 'pay', to: 'credit_cards#pay'
      post 'delete', to: 'credit_cards#delete'
    end
  end

  root 'items#index'
  resources :items do
    collection do
      get 'signup'
      get 'search'
      get 'ransack'
      get 'get_category_children', defaults: { fomat: 'json'}
      get 'get_category_grandchildren', defaults: { fomat: 'json'}
    end
    member do
      post   '/like/:item_id', to: 'likes#like',   as: 'like'
      delete '/like/:item_id', to: 'likes#unlike', as: 'unlike'
    end
    resources :messages, only:[:create,:update,:destroy] do
      member do
        get 'restore'
      end
    end
    resources :purchase, only: [:index] do
      collection do
        post 'pay', to: 'purchase#pay'
        get 'done', to: 'purchase#done'
      end
    end
  end

  resources :categories, only: [:index] do
    member do
      get 'parent'
      get 'child'
      get 'grandchild'
    end
  end
   
  resources :mypages, only: [:index] do
    collection do
      get 'logout'
      get :likes
    end
  end
  scope :mypages do
    resources :cards, only: [:index]
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

  before_action :category_parent_array

  def index
    @card = CreditCard.where(user_id: current_user.id).first
    if @card.present?
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @default_card_information = customer.cards.retrieve(@card.card_id)
      @default_card_brand = @default_card_information.brand      
      case @default_card_brand
      when "Visa"
        @default_card_src = "visa.svg"
      when "JCB"
        @default_card_src = "jcb.svg"
      when "MasterCard"
        @default_card_src = "master-card.svg"
      when "American Express"
        @default_card_src = "american_express.svg"
      when "Diners Club"
        @default_card_src = "dinersclub.svg"
      when "Discover"
        @default_card_src = "discover.svg"
      when "SaisonCard"
        @default_card_src = "saison-card.svg"
      end
    end
  end

  private
  def category_parent_array
    @category_parent_array = Category.where(ancestry: nil) 
  end

end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/index.html.haml
- breadcrumb :mypage_cards

= render partial: "items/header"
= render partial: "items/breadcrumbs"

.Mypage
  .Mypage__Wrapper
    .Mypage__Wrapper__Side
      %ul
        %li.Mypage__Wrapper__Side__list
          = link_to "マイページ", mypages_path
          = icon('fa','chevron-right')
        %li.Mypage__Wrapper__Side__list
          = link_to "お知らせ", "#"
          = icon('fa','chevron-right')
        %li.Mypage__Wrapper__Side__list
          = link_to "いいね！一覧", likes_mypages_path
          = icon('fa','chevron-right')
        %li.Mypage__Wrapper__Side__list
          = link_to "出品する", new_item_path
          = icon('fa','chevron-right')
        %li.Mypage__Wrapper__Side__list
          = link_to "出品した商品-出品中", "#"
          = icon('fa','chevron-right')
        %li.Mypage__Wrapper__Side__list
          = link_to "出品した商品-売却済み", "#"
          = icon('fa','chevron-right')
        
      %ul.Mypage__Wrapper__Side__unli  
        設定
        %li.Mypage__Wrapper__Side__list
          = link_to "プロフィール", "#"
          = icon('fa','chevron-right')
        %li.Mypage__Wrapper__Side__list
          = link_to "発送元・お届け先住所変更", "#"
          = icon('fa','chevron-right')
        %li.Mypage__Wrapper__Side__list
          = link_to "支払い方法", cards_path, class: "PageActive"
          = icon('fa','chevron-right')
        %li.Mypage__Wrapper__Side__list
          = link_to "メール/パスワード", "#"
          = icon('fa','chevron-right')
        %li.Mypage__Wrapper__Side__list
          = link_to "本人情報", "#"
          = icon('fa','chevron-right')
        %li.Mypage__Wrapper__Side__list
          = link_to "ログアウト", logout_mypages_path
          = icon('fa','chevron-right')
    .Mypage__Wrapper__Main
      - if @card.present?
        %section.mypage-content__chapter-container
          %h2.card-main__chapter-head
            支払い方法
          .card-main__inner
            %section
              .card-main__content
                %h3.card-main__chapter-sub-head
                  クレジットカード一覧
              %ul.mypage-content__payment-list
                %li
                  .card-main__content.card-main__content-form{ action: '#', method: 'GET' }
                    %div
                      = image_tag "#{@default_card_src}", width: '49', height: '15', alt: @default_card_brand, id: "card_image",class:"card__card-main__mask__contents__content__menu__brand"
                    .mypage-content__payment-num
                      = "**** **** **** " + @default_card_information.last4
                    .mypage-content__payment-num
                      - exp_month = @default_card_information.exp_month.to_s
                      - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
                      = exp_month + ' / ' + exp_year
                    = form_tag(delete_credit_cards_path, method: :post, id: 'charge-form',  name: 'inputForm', class: 'mypage-content__card--form') do
                      %input{ type: 'hidden', name: 'card_id', value: '' }
                      %button.mypage-content__payment-remove 削除する
            .mypage-content__not-regist
              = link_to '#', target: '_blank' do
                %span 支払い方法について
                = icon 'fas', 'chevron-right'
      - else 
        .Mypage__Wrapper__Main__CardTitle
          支払い方法
        .Mypage__Wrapper__Main__CardInner
          .Mypage__Wrapper__Main__CardInner__title
            クレジットカード一覧
          .Mypage__Wrapper__Main__CardInner__add
            = link_to new_credit_card_path, class: "Mypage__Wrapper__Main__CardInner__add--link" do
              %i.fa.fa-credit-card クレジットカードを追加する 
= render partial: "items/footer" 